repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: mix-format
        name: mix format
        entry: mix format
        language: system
        types: [elixir]
        pass_filenames: false
